version: "3.9"

services:
  vision-api:
    build: ./vision_api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ~/.cache/biomedclip:/root/.cache/biomedclip
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_VISION_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ANTHROPIC_API_KEY=${NEXT_PUBLIC_ANTHROPIC_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - vision-api
    restart: unless-stopped 